### PR TITLE
fix: Query multiple returns error for timeseries

### LINKED ISSUE #52: bug: Query service doesn't validate schema_id on QueryMultiple route
As in title. It seems as something that some day may cause problems. But may as well not. We need to discuss whether to ignore this behaviour or change it.

### PR DESCRIPTION
**Pull request by frondeus**
fixes #52

### CODE REVIEW

File: crates/query-router/src/handler.rs [hunk 1]
```diff
@@ -80,12 +80,22 @@ pub async fn query_multiple(
...
-    let (query_address, _) = cache.get_schema_info(schema_id).await?;
+    let (query_address, schema_type) = cache.get_schema_info(schema_id).await?;
 
     let object_ids = object_ids.split(',').map(str::to_owned).collect();
-    let values = rpc::query_service::query_multiple(object_ids, query_address.clone())
-        .await
-        .map_err(Error::ClientError)?;
+
+    let values = match schema_type {
+        SchemaType::DocumentStorage => {
```
Comment (Kononnable) [inline crates/query-router/src/handler.rs:88]: `If let` might be nicer if only DS is allowed here.

**Review by Kononnable — APPROVED** [review]
